CREATE TABLE SRC_USER (
	FIRST_NAME CHARACTER VARYING (50),
	LAST_NAME CHARACTER VARYING (50),
	MIDDLE_NAME CHARACTER VARYING (50),
	MANABADI_ID CHARACTER VARYING (200),
	EMAIL CHARACTER VARYING (200),
	CONTACT_NUMBER CHARACTER VARYING (50),
	ADDRESS CHARACTER VARYING (250),
	GENDER CHARACTER VARYING (10)
);



CREATE TABLE SRC_REGION (
	REGION_NAME CHARACTER VARYING (100),
	REGIONAL_COORDINATOR TEXT
);


CREATE TABLE SRC_CENTER (
    NAME CHARACTER VARYING (100),
	ACTIVE_STATUS BOOLEAN,
	ADDRESS TEXT,
	GEO TEXT,
	REGION TEXT,
	COORDINATORS TEXT
);





CREATE TABLE SRC_COURSE_ENROLLMENT (
	ID CHARACTER VARYING (50),
	ACADEMIC_GRADE CHARACTER VARYING (10),
	ACADEMIC_SCHOOL TEXT,
	ACADEMIC_YEAR CHARACTER VARYING (50),
	AVERAGE_SCORE  CHARACTER VARYING (50),
	RESULT CHARACTER VARYING (50),
	COURSE_COMPLETED BOOLEAN,
	SHIRT_SIZE CHARACTER VARYING (10),
	STATUS CHARACTER VARYING (50),
	STUDENT_IMAGE TEXT,
	STUDENT_KEY TEXT,
	STUDENT_MANABADI_ID CHARACTER VARYING (100),
	CENTER_NAME CHARACTER VARYING (50),
	COURSE_NAME CHARACTER VARYING (50)
);


