CREATE OR REPLACE PROCEDURE SP_POPULATE_ADDRESS(P_ETL_USER_ID UUID)
LANGUAGE PLPGSQL AS $$

DECLARE

v_ADDRESS_id ADDRESS.ID % type;
V_ADDRESS ADDRESS.ADDRESS%TYPE;
V_CITY ADDRESS.CITY%TYPE := 'NY';
V_COUNTRY ADDRESS.COUNTRY%TYPE := 'USA';
V_STATE ADDRESS.STATE%TYPE := 'Manhattan';
V_ZIPCODE ADDRESS.ZIPCODE%TYPE := '10001';

CUR_SRC_ADDRESS CURSOR FOR 
SELECT ADDRESS FROM SRC_USER
UNION
SELECT ADDRESS FROM SRC_CENTER
UNION
SELECT ACADEMIC_SCHOOL FROM SRC_COURSE_ENROLLMENT;

BEGIN
FOR RECORD IN CUR_SRC_ADDRESS
LOOP
v_ADDRESS_id := gen_random_uuid();
V_ADDRESS:=RECORD.ADDRESS;

RAISE NOTICE 'VALUE: %', RECORD;
INSERT INTO PUBLIC.ADDRESS(
                         ID,
						 ADDRESS,
						 CITY,
					     COUNTRY,
						 STATE,
						 ZIPCODE,
						 CREATED_BY,
						 UPDATED_BY
						 
						) 
						VALUES (
						v_ADDRESS_id,
						V_ADDRESS,
						V_CITY,
						V_COUNTRY,
						V_STATE,
						V_ZIPCODE,
						P_ETL_USER_ID,
						P_ETL_USER_ID
						
					   );

END LOOP;
END;
$$


--call SP_POPULATE_ADDRESS('813292a4-ad8c-4e3c-9669-d76c3b9d6cee')

--select * from address